# Generated by Django 4.2.6 on 2023-11-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='author',
            new_name='user1',
        ),
    ]
