# Generated by Django 4.2.5 on 2023-11-21 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_gametur_photo_alter_tournament_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametur',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=12, verbose_name='Телефон пользователя')),
                ('userPhone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Телефон пользователя',
                'verbose_name_plural': 'Телефоны пользователей',
            },
        ),
    ]
